import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { InventoryItem } from './types';

// Extend jsPDF type for autotable
declare module 'jspdf' {
    interface jsPDF {
        autoTable: (options: any) => jsPDF;
        lastAutoTable: { finalY: number };
    }
}

// ─── HELPERS ─────────────────────────────────────────────────

function formatDate(): string {
    const now = new Date();
    const dd = String(now.getDate()).padStart(2, '0');
    const mm = String(now.getMonth() + 1).padStart(2, '0');
    const yyyy = now.getFullYear();
    const hh = String(now.getHours()).padStart(2, '0');
    const min = String(now.getMinutes()).padStart(2, '0');
    return `${dd}/${mm}/${yyyy} ${hh}:${min}`;
}

function formatNumber(n: number): string {
    return n.toLocaleString('id-ID');
}

// ─── REORDER REPORT ──────────────────────────────────────────

/**
 * Generate a PDF report for items needing reorder (CRITICAL + REORDER status).
 */
export function generateReorderReport(
    items: InventoryItem[],
    branchName?: string,
    warehouseName?: string
): Buffer {
    const reorderItems = items.filter(i => i.status === 'CRITICAL' || i.status === 'REORDER');

    const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

    // Header
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('LAPORAN REORDER INVENTORY', 148, 15, { align: 'center' });

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const subtitle = [
        `Tanggal: ${formatDate()}`,
        branchName ? `Cabang: ${branchName}` : '',
        warehouseName ? `Gudang: ${warehouseName}` : '',
    ].filter(Boolean).join('  |  ');
    doc.text(subtitle, 148, 22, { align: 'center' });

    // Summary
    const criticalCount = reorderItems.filter(i => i.status === 'CRITICAL').length;
    const reorderCount = reorderItems.filter(i => i.status === 'REORDER').length;
    doc.setFontSize(9);
    doc.text(`Total: ${reorderItems.length} item  |  Critical: ${criticalCount}  |  Reorder: ${reorderCount}`, 14, 30);

    // Table
    const tableData = reorderItems.map((item, idx) => [
        idx + 1,
        item.itemNo,
        item.name.length > 35 ? item.name.substring(0, 35) + '...' : item.name,
        item.unit,
        formatNumber(item.stock),
        formatNumber(item.reorderPoint),
        formatNumber(item.safetyStock),
        item.poOutstanding > 0 ? formatNumber(item.poOutstanding) : '-',
        formatNumber(item.netShortage),
        item.suggestedOrder > 0 ? formatNumber(item.suggestedOrder) : '-',
        item.status,
    ]);

    doc.autoTable({
        startY: 34,
        head: [['No', 'Kode Item', 'Nama Barang', 'Satuan', 'Stock', 'ROP', 'Safety', 'PO Outst.', 'Shortage', 'Saran Order', 'Status']],
        body: tableData,
        theme: 'grid',
        headStyles: { fillColor: [30, 64, 175], fontSize: 8, halign: 'center' },
        bodyStyles: { fontSize: 7 },
        columnStyles: {
            0: { halign: 'center', cellWidth: 10 },
            1: { cellWidth: 25 },
            2: { cellWidth: 55 },
            3: { halign: 'center', cellWidth: 15 },
            4: { halign: 'right', cellWidth: 18 },
            5: { halign: 'right', cellWidth: 18 },
            6: { halign: 'right', cellWidth: 18 },
            7: { halign: 'right', cellWidth: 20 },
            8: { halign: 'right', cellWidth: 20 },
            9: { halign: 'right', cellWidth: 22 },
            10: { halign: 'center', cellWidth: 18 },
        },
        didParseCell: (data: any) => {
            // Color CRITICAL rows red
            if (data.section === 'body' && data.row.raw) {
                const status = data.row.raw[10];
                if (status === 'CRITICAL') {
                    data.cell.styles.fillColor = [254, 226, 226]; // red-100
                } else if (status === 'REORDER') {
                    data.cell.styles.fillColor = [255, 237, 213]; // orange-100
                }
            }
        },
        margin: { left: 14, right: 14 },
    });

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'italic');
        doc.text(`Halaman ${i} dari ${pageCount}  —  Generated by Inventory Analysis System`, 148, 200, { align: 'center' });
    }

    return Buffer.from(doc.output('arraybuffer'));
}

// ─── ALERT REPORT ────────────────────────────────────────────

/**
 * Generate a PDF report mirroring the Alert page (Critical + Reorder + Dead Stock).
 */
export function generateAlertReport(
    items: InventoryItem[],
    branchName?: string,
    warehouseName?: string
): Buffer {
    const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

    // Header
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('LAPORAN ALERT INVENTORY', 148, 15, { align: 'center' });

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const subtitle = [
        `Tanggal: ${formatDate()}`,
        branchName ? `Cabang: ${branchName}` : '',
        warehouseName ? `Gudang: ${warehouseName}` : '',
    ].filter(Boolean).join('  |  ');
    doc.text(subtitle, 148, 22, { align: 'center' });

    const criticalItems = items.filter(i => i.status === 'CRITICAL');
    const reorderItems = items.filter(i => i.status === 'REORDER');
    const deadStockItems = items.filter(i => i.demandCategory === 'DEAD' && i.stock > 0);

    let currentY = 30;

    // ── Section 1: Critical ──
    if (criticalItems.length > 0) {
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(220, 38, 38);
        doc.text(`⚠ CRITICAL (${criticalItems.length} item) — Di bawah Safety Stock`, 14, currentY);
        doc.setTextColor(0, 0, 0);

        doc.autoTable({
            startY: currentY + 3,
            head: [['No', 'Kode Item', 'Nama Barang', 'Stock', 'Safety Stock', 'PO Outst.', 'Shortage', 'Status']],
            body: criticalItems.map((item, idx) => [
                idx + 1,
                item.itemNo,
                item.name.length > 40 ? item.name.substring(0, 40) + '...' : item.name,
                `${formatNumber(item.stock)} ${item.unit}`,
                formatNumber(item.safetyStock),
                item.poOutstanding > 0 ? `+${formatNumber(item.poOutstanding)}` : '-',
                formatNumber(item.netShortage),
                'CRITICAL',
            ]),
            theme: 'grid',
            headStyles: { fillColor: [220, 38, 38], fontSize: 8 },
            bodyStyles: { fontSize: 7, fillColor: [254, 226, 226] },
            margin: { left: 14, right: 14 },
        });

        currentY = doc.lastAutoTable.finalY + 8;
    }

    // ── Section 2: Reorder ──
    if (reorderItems.length > 0) {
        if (currentY > 170) { doc.addPage(); currentY = 15; }

        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(234, 88, 12);
        doc.text(`🔔 REORDER (${reorderItems.length} item) — Di bawah Reorder Point`, 14, currentY);
        doc.setTextColor(0, 0, 0);

        doc.autoTable({
            startY: currentY + 3,
            head: [['No', 'Kode Item', 'Nama Barang', 'Stock', 'ROP', 'PO Outst.', 'Shortage', 'Saran Order']],
            body: reorderItems.map((item, idx) => [
                idx + 1,
                item.itemNo,
                item.name.length > 40 ? item.name.substring(0, 40) + '...' : item.name,
                `${formatNumber(item.stock)} ${item.unit}`,
                formatNumber(item.reorderPoint),
                item.poOutstanding > 0 ? `+${formatNumber(item.poOutstanding)}` : '-',
                formatNumber(item.netShortage),
                item.suggestedOrder > 0 ? formatNumber(item.suggestedOrder) : '✓',
            ]),
            theme: 'grid',
            headStyles: { fillColor: [234, 88, 12], fontSize: 8 },
            bodyStyles: { fontSize: 7, fillColor: [255, 237, 213] },
            margin: { left: 14, right: 14 },
        });

        currentY = doc.lastAutoTable.finalY + 8;
    }

    // ── Section 3: Dead Stock ──
    if (deadStockItems.length > 0) {
        if (currentY > 170) { doc.addPage(); currentY = 15; }

        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(100, 116, 139);
        doc.text(`💀 DEAD STOCK (${deadStockItems.length} item) — Tidak ada penjualan`, 14, currentY);
        doc.setTextColor(0, 0, 0);

        const deadStockValue = deadStockItems.reduce((sum, i) => sum + i.stockValue, 0);

        doc.autoTable({
            startY: currentY + 3,
            head: [['No', 'Kode Item', 'Nama Barang', 'Stock', 'Satuan', 'Nilai Stock', 'Stock Age (hari)']],
            body: deadStockItems.slice(0, 50).map((item, idx) => [
                idx + 1,
                item.itemNo,
                item.name.length > 40 ? item.name.substring(0, 40) + '...' : item.name,
                formatNumber(item.stock),
                item.unit,
                `Rp ${formatNumber(item.stockValue)}`,
                formatNumber(item.stockAgeDays),
            ]),
            theme: 'grid',
            headStyles: { fillColor: [100, 116, 139], fontSize: 8 },
            bodyStyles: { fontSize: 7, fillColor: [241, 245, 249] },
            margin: { left: 14, right: 14 },
        });

        // Total dead stock value
        const afterY = doc.lastAutoTable.finalY + 4;
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.text(`Total Nilai Dead Stock: Rp ${formatNumber(deadStockValue)}`, 14, afterY);
    }

    // Footer on all pages
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(128, 128, 128);
        doc.text(`Halaman ${i} dari ${pageCount}  —  Generated by Inventory Analysis System`, 148, 200, { align: 'center' });
    }

    return Buffer.from(doc.output('arraybuffer'));
}
